langchain4j.ollama.chat-model.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=qwen3:8b
langchain4j.ollama.chat-model.timeout=120s
langchain4j.ollama.streaming-chat-model.base-url=http://localhost:11434
langchain4j.ollama.streaming-chat-model.model-name=qwen3:8b
langchain4j.ollama.streaming-chat-model.timeout=120s
server.port=8081

# Debug tool execution
logging.level.dev.langchain4j=DEBUG

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379